# Generated by Django 4.0.5 on 2022-07-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
