# Generated by Django 4.0.5 on 2022-07-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_cart_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleuser',
            name='ordered',
        ),
        migrations.AddField(
            model_name='article',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
