# Generated by Django 4.0.5 on 2022-07-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_articleuser_ordered_article_ordered'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleUser',
        ),
    ]
