# Generated by Django 4.0.5 on 2022-07-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
