# Generated by Django 4.0.5 on 2022-07-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='qte',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
