# Generated by Django 4.0.5 on 2022-07-09 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_article_qte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='qte',
        ),
    ]
