# Generated by Django 4.0.5 on 2022-07-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_cart_qte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='qte',
        ),
        migrations.AddField(
            model_name='cart',
            name='qte',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
