# Generated by Django 4.0.5 on 2022-07-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_article_qte_cart_qte'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='num_order',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
