# Generated by Django 4.0.5 on 2022-07-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_cart_date_added_remove_cart_ordered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date_order',
        ),
        migrations.AddField(
            model_name='article',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
