# Generated by Django 4.0.5 on 2022-07-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_article_date_order_article_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='activate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_added',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
